services:
  api1: &api
    image: ghcr.io/lemesdaniel/floating-finch-zig:v2
    platform: linux/amd64
    networks: [backend]
    environment:
      INDEX_PATH: /app/data/index.bin
      BIND_PORT: "8080"
      IVF_NPROBE: "4"
      IVF_BBOX_REPAIR: "true"
      IVF_REPAIR_MIN: "1"
      IVF_REPAIR_MAX: "4"
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "165MB"

  api2:
    <<: *api
    environment:
      INDEX_PATH: /app/data/index.bin
      BIND_PORT: "8080"
      IVF_NPROBE: "4"
      IVF_BBOX_REPAIR: "true"
      IVF_REPAIR_MIN: "1"
      IVF_REPAIR_MAX: "4"

  nginx:
    image: nginx:1.27-alpine
    platform: linux/amd64
    depends_on: [api1, api2]
    networks: [backend]
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "20MB"

networks:
  backend:
    driver: bridge
