services:
  api1: &api
    image: ghcr.io/lemesdaniel/floating-finch-zig:v16
    platform: linux/amd64
    networks: [backend]
    environment:
      INDEX_PATH: /app/data/index.bin
      UDS_PATH: /sockets/api1.sock
      IVF_NPROBE: "4"
      IVF_FAST_PROBE: "4"
      IVF_RESCUE_PROBE: "8"
      IVF_SHORTLIST: "16"
      IVF_AMBIG_MIN: "2"
      IVF_AMBIG_MAX: "3"
      IVF_BBOX_REPAIR: "true"
      IVF_REPAIR_MIN: "1"
      IVF_REPAIR_MAX: "4"
    volumes:
      - sockets:/sockets
    security_opt:
      - seccomp=unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "165MB"

  api2:
    <<: *api
    environment:
      INDEX_PATH: /app/data/index.bin
      UDS_PATH: /sockets/api2.sock
      IVF_NPROBE: "4"
      IVF_FAST_PROBE: "4"
      IVF_RESCUE_PROBE: "8"
      IVF_SHORTLIST: "16"
      IVF_AMBIG_MIN: "2"
      IVF_AMBIG_MAX: "3"
      IVF_BBOX_REPAIR: "true"
      IVF_REPAIR_MIN: "1"
      IVF_REPAIR_MAX: "4"

  nginx:
    image: nginx:1.27-alpine
    platform: linux/amd64
    depends_on: [api1, api2]
    networks: [backend]
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/sockets
    security_opt:
      - seccomp=unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.core.somaxconn: 4096
    deploy:
      resources:
        limits:
          cpus: "0.18"
          memory: "20MB"

volumes:
  sockets:

networks:
  backend:
    driver: bridge
