worker_processes 2;
worker_rlimit_nofile 65535;
error_log /dev/null crit;
pid /tmp/nginx.pid;

events {
    worker_connections 4096;
    multi_accept off;
    use epoll;
}

stream {
    upstream backend {
        server unix:/sockets/api1.sock;
        server unix:/sockets/api2.sock;
    }

    server {
        listen 9999 reuseport backlog=4096;
        proxy_pass backend;
        proxy_connect_timeout 1s;
        proxy_timeout 30s;
    }
}
